version: '3'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      - ./src/plugins/:/var/www/html/wp-content/plugins/ # Plugin development
      - ./src/themes/:/var/www/html/wp-content/themes/ # Theme development
      - ./src/uploads/:/var/www/html/wp-content/uploads/ # Theme uploads development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"
    depends_on:
      - db
    links:
      - db
    networks:
      - wplocaldocker

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"
    depends_on:
      - db
      - wp
    networks:
      - wplocaldocker

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    links:
      - db:db
    networks:
      - wplocaldocker

  db:
    image: mysql:${MYSQL_VERSION} # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:${MYSQL_EXPOSED_PORT}:3306 # change ip if required
   # command: [
        #'--default_authentication_plugin=mysql_native_password',
    #    '--character-set-server=utf8mb4',
     #   '--collation-server=utf8mb4_unicode_ci'
    #]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - wplocaldocker
     
networks:
  wplocaldocker:
    driver: bridge

volumes:
  db_data:
