#!/usr/bin/env bash
container="wp"
if [ "$2" != "" ]
then
    container=$2
fi

if [ -z "$1" ]
  then
    docker-compose exec --user www-data "$container" bash
else
    docker-compose exec --user $1 "$container" bash
fi